### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by heinsaar** [heinsaar/masis#2]
## Kaizen 1.0

**Library**
- [x] Add all STL containers
- [x] #3
- [ ] Fuse useful stuff from Qt, Python & JS
- [ ] Ensure all entities are in their right namespace
- [ ] Ensure compilation shows no dangerous warnings
- [ ] Ensure all `kaizen.h` functions are thoroughly tested 
- [x] Ensure all `zen` entities have small usage examples in code

**Metrics & Tests**
- [ ] Add static analysis and integrate with the flow
- [ ] Show & visualize LOC growth for the past year
- [x] Show & visualize test cases per LOC for non-test dirs

**DevOps**
- [x] CI: Set up automated build
- [ ] CI: Set up automated tests
- [ ] CI: Run & cross-check appropriate tests on dev repo structure as well as on single header
- [ ] Create benchmarks & their report format

## Kaizen 2.0
- [ ] Add performance tests
- [ ] Maybe split into different translation units to parallelize compilation
- [ ] Devise a way to reuse zen code internally, or keep deliberately decoupled?
       _(in 1.0 lib headers are deliberately mostly unaware of each other)_
- [ ] Package Kaizen into a module
